name: flutter_test_future # 和包相关
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.17
#格式用+号分割，这个的含义在 Android 中的意思为 versionName+versionCode。IOS 的话暂时不知道，不过应该差不多

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # 国际化
    sdk: flutter
  get: ^4.6.1 # 4.6.3不支持SDK2.15，必须大于2.15
  animations: ^2.0.2
  shared_preferences: ^2.0.9
  sqflite: ^2.0.1  # 不支持windows，可使用sqflite_common_ffi
  sqflite_common_ffi: ^2.1.0
  path_provider: ^2.0.8
  # file: ^6.1.2
  file_picker: ^4.2.8
  # image_picker: ^0.8.4+4 # 不是从图库中选择
  # images_picker: ^1.2.10 # 要求minSdkVersion 21，但不行
  # multi_image_picker2: ^5.0.2 # 自己生成的图库，很不好找
  # permission_handler: ^8.3.0 # 不支持windows
  # share: ^2.0.4
  # share_plus: ^3.0.4
  # flutter_share: ^2.0.0
  webdav_client: ^1.1.2
  oktoast: ^3.1.5
  # download: any
  # search_app_bar_page: ^2.1.2 # 添加上导致出错：
  #   * What went wrong:
  # Execution failed for task ':connectivity:compileDebugJavaWithJavac'.
  # > Compilation failed; see the compiler error output for details.
  # flutter_search_bar: ^2.1.0
  # search_page: ^2.0.0+1
  salomon_bottom_bar: ^3.2.0
  # animations: ^2.0.2
  # proste_route_animation: ^2.0.2 # 路由过渡动画
  scroll_bottom_navigation_bar: ^4.0.0
  scroll_app_bar: ^2.0.0
  # multiselect_scope: ^0.2.0 # 切换顶部栏时会出错
  # flutter_keyboard_visibility: ^5.1.0
  # keyboard_utils: ^1.3.3
  dio: ^4.0.4
  html: ^0.15.0
  cached_network_image: ^3.2.0 # 缓存图片。不支持windows
  # photo_view: ^0.13.0 # 点击查看图片
  easy_image_viewer: ^1.0.3
  archive: ^3.1.8
  # flutter_screenutil: ^5.0.2
  # flutter_autosize_screen: ^1.0.1 # get不了
  # desktop_window: ^0.4.0 # 添加导致run不了：无法运行“rc.exe”
  path: ^1.8.0
  # package_info: ^2.0.2 # 查询版本号，报错MissingPluginException
  package_info_plus: ^1.4.2
  # url_launcher: ^6.0.17 # 使用默认浏览器打开链接。LINK : fatal error LNK1158: 无法运行“rc.exe”
  url_launcher: ^6.1.0
  transparent_image: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/defaultAnimeCover.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  
  # fonts:
  # - family: yuan
  #   fonts:
  #     - asset: assets/fonts/未来圆SC Regular.ttf  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
